        /*
* Java bean class
* Created on 1 avr. 2015 ( Date ISO 2015-04-01 - Time 12:07:54 )
* Generated by Telosys Tools Generator ( version 2.1.1 )
*/

package org.demo.bean;

import java.io.Serializable;

import java.util.Date;

import org.mongodb.morphia.annotations.Entity;
import org.mongodb.morphia.annotations.Id;

/**
* Entity bean
*
* @author Telosys Tools Generator
*
*/
@Entity("employees")
public class Employee implements Serializable
{
    private static final long serialVersionUID = 1L;

    private Date birthDate;
    private String firstName;
    @Id
    private Integer id;
    private String countryCode;

    /**
     * Default constructor
     */
    public Employee()
    {
        super();
    }
    
    /**
     * Set the "birthDate" field value
     * @param birthDate
     */
    public void setBirthDate( Date birthDate )
    {
        this.birthDate = birthDate;
    }
        
    /**
     * Get the "birthDate" field value
     * @return the field value
     */
    public Date getBirthDate()
    {
        return this.birthDate;
    }
        
    /**
     * Set the "firstName" field value
     * @param firstName
     */
    public void setFirstName( String firstName )
    {
        this.firstName = firstName;
    }
        
    /**
     * Get the "firstName" field value
     * @return the field value
     */
    public String getFirstName()
    {
        return this.firstName;
    }
        
    /**
     * Set the "id" field value
     * @param id
     */
    public void setId( Integer id )
    {
        this.id = id;
    }
        
    /**
     * Get the "id" field value
     * @return the field value
     */
    public Integer getId()
    {
        return this.id;
    }
        
    /**
    * Set the "countryCode" link value
    * @param countryCode
    */
    public void setCountryCode( String countryCode )
    {
        this.countryCode = countryCode;
    }
        
    /**
    * Get the "countryCode" link value
    * @return the link value
    */
    public String getCountryCode()
    {
        return this.countryCode;
    }
    
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(birthDate);
        sb.append("|");
        sb.append(firstName);
        sb.append("|");
        sb.append(id);
        return sb.toString(); 
    } 


}
