/*
 * Java bean class
 * Created on 30 mars 2015 ( Date ISO 2015-03-30 - Time 14:41:59 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.demo.dao;

import java.io.Serializable;


import com.mongodb.DBObject;
import com.mongodb.Mongo;
import com.mongodb.MongoClient;
import com.mongodb.QueryBuilder;
import org.mongodb.morphia.Datastore;
import org.mongodb.morphia.Morphia;

import java.net.UnknownHostException;
import java.util.ArrayList;
import java.util.List;

import org.demo.bean.Country;

/**
 * DAO : Countrys
 *
 * @Country Telosys Tools Generator
 *
 */
public class CountryDao {

    public static String COLLECTION = "Countrys";

    private final String host;
    private final Integer port;
    private final String databaseName;

    public CountryDao(String host, Integer port, String databaseName) {
        this.host = host;
        this.port = port;
        this.databaseName = databaseName;
    }

    private Datastore getCountryDatastore() {
        try {
            MongoClient mongo = new MongoClient(this.host, this.port);
            Datastore ds = new Morphia().createDatastore(mongo, this.databaseName);
            return ds;
        } catch (UnknownHostException e) {
            throw new RuntimeException(e);
        }
    }

    public void save(Country country) {
        getCountryDatastore().save(country);
    }

    public void remove(Country country) {
        getCountryDatastore().delete(country);
    }

    public List<Country> findAll() {
        List<Country> countrys = getCountryDatastore().find(Country.class).asList();
        return countrys;
    }

    public Country findByLabel(String label) {
        Country country = getCountryDatastore().find(Country.class, "label", label).get();
        return country;
    }

    public Country findByCode(String code) {
        Country country = getCountryDatastore().find(Country.class, "code", code).get();
        return country;
    }


}
